spring:
  config:
    activate:
      on-profile: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

logging:
  level:
    com.jobtantra: INFO
